- docs/source/index.rst
- psrqpy/__init__.py
- psrqpy/config.py
- psrqpy/search.py
- psrqpy/utils.py
A function, `get_catalogue()`, has been added that downloads the entire ATNF catalogue database and returns it as an astropy table. This currently does not return the parameter errors. This function is based on
the code in [ATNF.ipynb](https://github.com/astrophysically/ATNF-Pulsar-Cat/blob/master/ATNF.ipynb) by @astrophysically.
@astrophysically - are you happy for me to use this code? I've added an attribution to you in the code documentation, but I can add you to the copyright statement as well if you want?
See also comment in #3.
> Add a function to download the entire catalogue

- psrqpy/__init__.py
- psrqpy/search.py
Following #13 I have made the code check if no pulsars are found, output an appropriate message, and just return `None`.
I have also changed the default warnings message to not output the code line number, and code line, that generates the message (I modified [this](https://pymotw.com/3/warnings/#formatting) example).
> More graceful exit when no pulsars found, and changed warnings message

- psrqpy/__init__.py
- psrqpy/utils.py
In the `get_catalogue()` function it uses urllib2 to download the ATNF catalogue tarball. However, this does not work for Python3, which no longer has urllib2. I've therefore changed to using the requests module instead. In Python3 the tarball content also has to be read as a BytesIO type rather than a StringIO type, so I've also fixed this.
> Remove use of urllib2

- psrqpy/__init__.py
- psrqpy/utils.py
- setup.py
After PR #16  `get_catalogue()` would still not work under Python 3 due to the strings being read in as byte types, and astropy's Table not liking this. I now decode the bytes to strings and it works.
On a separate note, I've added the ability to publish a test package to the [PyPI testing site](https://test.pypi.org/).
> Fix get_catalogue()

- psrqpy/search.py
Note, this includes the other PR I submitted. So (if that gets accepted) this is just for the second commit, which changes lines 979 to 981 (just adds in the labels). 
Rational:
For the specially plotted pulsars (i.e. Binary, Pulsar Thermal X-ray)
etc, adds the label. This is subsequently overwritten by the ax.legend
call. However, if someone then adds other objects to the figure
generated by psrqpy, this ensures they are saved in the
`legend_handles_labels()` attribute.
> Add labels by default

- psrqpy/__init__.py
Add software citation information into the package itself (see, e.g. slide 31 of [this presentation](https://speakerdeck.com/arfon/how-to-get-and-give-career-credit-for-software) by @arfon).
> Add citation information

- psrqpy/search.py
Re-adds missing SNR (and RRAT) label from #22.
> search.py: fix missing legend labels

- README.md
- docs/source/index.rst
- psrqpy/__init__.py
- psrqpy/search.py
The `JNAME` parameter will now be automatically queried by all searches, unless explicitly told not to with the `nojname` argument.
> Make JNAME be a parameter that is automatically queried by all searches

- psrqpy/utils.py
I've changed the `get_catalogue()` function to significantly speed it up. Rather than initially creating an astropy table and having to continuously update the number of rows and masked columns, it now just creates a list of dictionaries and uses these to create a table at the end.
@respiewak - would you be able to check this out? It should be flexible enough to read in a database with arbitrary additional parameter values.
> Changes to `get_catalogue` to speed it up significantly

- MANIFEST.in
- setup.py
The `requirements.txt` file should be included in the package data, so this PR adds it.
> Add requirements.txt file to MANIFEST

- requirements.txt
[`GM_sun` was added in astropy 2.0](https://github.com/astropy/astropy/blob/8d97a4f9d62a76629ac9b86ebd1c22c340ea7a0e/CHANGES.rst#astropyconstants-7) and is required for `psrqpy` to import successfully.
[`pandas 0.21.0` is required for `Series.isna`](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.21.0.html#na-naming-changes).
> Set minimum versions

- psrqpy/utils.py
It seems that the way the references are stored in the ATNF pulsar catalogue tarball has changed. this means the the current `get_references` function is broken. This PR changes the parsing of the references to make this work again. It also adds a decorator around the function to show a warning if using an older version of the catalogue.
Closes #62.
> Fix how references are parsed

- psrqpy/search.py
I've chosen to use the `pre-v4.0` defaults.
Closes #63.
> Set default for astropy galactocentric coordinates

- psrqpy/pulsar.py
- test/query_test.py
This PR allows the `_REF` attribute to be used to query parameter references within a `Pulsar` object.
> Allow references to be queries within Pulsar object

- psrqpy/utils.py
Catch an exception if there is a problem converting RAJ/DECJ strings to degrees (specifically in ATNF catalogue v1.64 there's an error in the DECJ value for J1623+5850, which causes the catalogue parsing to fail).
- refs #73
> Resolve "ATNF typo causing QueryATNF to fail"

- .travis.yml
- docs/source/index.rst
- psrqpy/config.py
- psrqpy/utils.py
- setup.py
- test/query_test.py
> Add ability to parse the globular cluster pulsar table

- psrqpy/utils.py
The way that values are stored in the galmsp table changed (see [8a6b1be6](https://github.com/astrogewgaw/galmsps/commit/8a6b1be63ba6dafa56a3b51f70963c04bcb7247e)). This broke how psrqpy parsed the data, which has now been fixed in this PR.
> Fix parsing of galactic MSP table following changes to galmsp repo

- psrqpy/search.py
This PR adds functionality to propagate the errors on ecliptical coordinates to equatorial coordinates. It uses a different algorithm to that in `psrcat` itself (see the `defineEquatorial` function in `defineParams.c`). It is not clear what the `psrcat` implementation does precisely.
This algorithm takes the errors in ecliptical coordinates and rotates them to the equatorial coordinate frame using the position angle between the North Ecliptical Pole and the North Equatorial Pole (taken from Jean Meeus' Astronomical Algorithms, 2nd edition, p. 100). Errors are corrected for `cos(ELAT)` and `cos(DECJ)` factors.
Comparison of the resulting errors on equatorial coordinates against the online PSRCAT results shows reasonable agreement.
> Propagate errors on ecliptical coordinates to equatorial (Fixes #89)

- .github/workflows/pypi.yml
- .gitignore
- .travis.yml
- MANIFEST.in
- README.md
- docs/source/index.rst
- optional_requirements.txt
- psrqpy/__init__.py
- psrqpy/config.py
- psrqpy/pulsar.py
- psrqpy/search.py
- psrqpy/utils.py
- pyproject.toml
- requirements.txt
- setup.cfg
- setup.py
- test_requirements.txt
This PR moves to using `setup.cfg` for all the build information. It also switches to using setuptools_scm for the version information. It also removes any residual Python 2 requirements.
Closes #84.
> Use setuptools scm for package version

- psrqpy/config.py
- psrqpy/search.py
- psrqpy/utils.py
The resolves #94 by allowing the user to specify the version of the ATNF catalogue to download, e.g.:
```python
from psrqpy import QueryATNF
q = QueryATNF(version="1.64")
print(q.get_version)
1.64
```
> Resolve "Version downloads"

- psrqpy/utils.py
Hi Matt,
I came across an issue with the DATE parameter (PR to follow shortly), and while looking at fixing it I found that psrqpy seemed to have a significantly reduced number of POSEPOCH values as compared to a query to psrcat. Digging into the psrcat source, it seems that if a value for POSEPOCH is not set for a source, psrcat will copy over the value from the PEPOCH parameter to fill in the gap.
I've run the pytest suite on the PR and this passes all tests. Any warnings also appeared in the current HEAD version. Though there will be a slight reduction in code coverage as I haven't written new tests.
> ❯ git symbolic-ref --short HEAD
> posepoch_from_pepoch
> ❯ pytest
> ============================= test session starts ==============================
> platform linux -- Python 3.9.5, …
> If POSEPOCH is not present, copy the value from PEPOCH

- psrqpy/search.py
- psrqpy/tests/query_test.py
- psrqpy/utils.py
Hi Matt,
In the current v1.1.6 on pip if "DATE" is requested all attempts to interact with the returned catalogue raise a key error as the DATE value is never derived from the catalogue. Here's a example of the issue I'm seeing:
```
Python 3.9.5 (default, May 11 2021, 08:20:37) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import psrqpy
In [2]: cat = psrqpy.QueryATNF(params = ['JNAME', 'SURVEY', 'DATE'])
cat.dataframe.
In [3]: cat.dataframe.head()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
....
KeyError: "['DATE'] not in index"
In [4]: cat
Out[4]: …
```
> Derive the value for the "DATE" parameter.

- psrqpy/pulsar.py
- psrqpy/search.py
- psrqpy/tests/query_test.py
- psrqpy/utils.py
Currently, if caching (the default) using the `QueryATNF` object, it actually only caches the downloaded ATNF catalogue tarball.  When generating new queries using `QueryATNF`, even using this cached file can take a few to tens of second to load (due partly to having to recalculate all the derived parameters. This PR instead caches and re-loaded the `QueryATNF` object itself, which is considerably quicker.
The default location of the cache objects has also been changed to be in a `~/.psrqpy` directory.
This supersedes #102.
> Cache QueryATNF object

- psrqpy/search.py
- psrqpy/tests/query_test.py
Fix a bug introduced in #103 that meant that if you loaded a local database file (and left the default setting of `cache=True`) that file would get cached and overwrite the full catalogue. This caused issues with testing due to the tests loading a local test database.
A check for a `UserWarning` has also been added in the tests.
> Prevent caching of local database files

- psrqpy/utils.py
Ran into an issue where I was getting an undefined error for an error variable while looking up an older version of the catalogue, turned out to be a side effect of a sub-function call that was using the same variable name for the error, except in that case it was never defined.
Better way of checking the return: ask requests to raise an error in the case that the download did not proceed as expected. ( https://requests.readthedocs.io/en/master/api/#requests.Response.raise_for_status )
Build is currently failing on my branch as the WVU website is returning 502s, so the MSP table checks cannot proceed (http://astro.phys.wvu.edu/GalacticMSPs/GalacticMSPs.txt)
Quick repro test (the v isn't meant to be in the version string):
```python
import psrqpy
query = psrqpy.QueryATNF(psrtype = "RRAT", …
```
> Fix an UnboundLocalError from psrcat tarball status check

- psrqpy/config.py
- psrqpy/pulsar.py
As of v1.68 (or maybe from 1.66/67 onwards), so pulsar have an S350 flux value. This can now be extracted from a psrqpy query. Note that there are no pulsars for which the S30, S10G, S20G and S50G are added yet, so these are not listed as parameters available within psrqpy yet.
> Add S350 flux value

- .github/workflows/build.yml
This PR patches the CI config for the `build.yml` workflow to run the workflow nightly. This should help catch issues like #116 sooner.
> Run the build workflow nightly at midnight

- psrqpy/utils.py
The parsing of the [glitch catalogue table](https://www.jb.man.ac.uk/pulsar/glitches/gTable.html) is currently [failing](https://github.com/mattpitkin/psrqpy/actions/runs/4258176268/jobs/7409127175). I think this is due to the inclusion of a glitch for PSR J1904-1629, which currently has several empty columns.  This PR (hopefully) fixes this by allowing `TypeError` as potential exception when parsing the values from a row in the table.
> Fix parsing of the glitch catalogue table

- psrqpy/tests/query_test.py
- psrqpy/utils.py
As mentioned in #129, the latest catalogue version has a distance for the Crab pulsar of 1.5 kpc rather than the previous value of 2 kpc. This breaks the test suite which compares the calculated derived gravitational wave parameters with those from the literature.  To fix this, for the moment, I've switched the tests to use the Vela pulsar. This is much closer and has a more precisely known distance that is unlikely to be subject to change.
Closes #129.
> Change derived gravitational wave parameter tests from Crab pulsar to Vela pulsar

- psrqpy/utils.py
Currently, when reading from the ATNF catalogue database files, the code assumes that all fields have an associated value, i.e., each lines consists of at least:
```txt
FIELD_NAME VALUE
```
There might be errors in the file where no value is specified. These should be harmless, but at the moment they break the code that parses the file. This PR fixes this by skipping lines that contain only a single item.
> Ignore database lines with no value

- psrqpy/search.py
This call was giving the following error:
>   File "psrqpy/search.py", line 2538, in get_ephemeris
>     outputdic['error'] = precstre.format(varerr) if varerr is not None else ''
>                          ^^^^^^^^
> UnboundLocalError: cannot access local variable 'precstre' where it is not associated with a value
> 
> 
when running
```
from psrqpy import QueryATNF
QueryATNF(psrs="J1627+3219").get_ephemeris("J1627+3219")
```
This MR should fix the logic regarding creating the strings to be printed.
> Update value, error formatting logic

- psrqpy/tests/query_test.py
> Resolves "Reference retrieval no longer works, so temporarily disable test"
