psrqpy/__init__.py, psrqpy/config.py, psrqpy/pulsar.py, psrqpy/search.py, psrqpy/utils.py, setup.py
This change creates proper `Pulsar` and `Pulsars` classes. This completes the issue in #2.
=> Moved Pulsar/Pulsars class to submodule

docs/source/index.rst, paper/paper.bib, paper/paper.md, paper/ppdot.png
A short paper has been written for submission to the [Journal of Open Source Software](http://joss.theoj.org/).
=> Create a paper for submission to JOSS

docs/source/index.rst, psrqpy/__init__.py, psrqpy/config.py, psrqpy/search.py
Allow user to be able to set the centre and radius of a circular boundary within which to search for pulsars,
From issue #23.
=> Circular boundary

docs/source/index.rst, psrqpy/config.py
Add the ATNF catalogue ["expert" mode](http://www.atnf.csiro.au/research/pulsar/psrcat/expert.html) parameters to those that can be queried as requested in #26.
=> Add "Expert" mode parameters

.travis.yml, psrqpy/config.py, test/query_test.py
… and have the correct combination of reference and error value as expected
=> Create a test script that checks that all the parameters can be readcorrectly

docs/source/index.rst, psrqpy/config.py, psrqpy/utils.py
I have added a function `get_glitch_catalogue` that parses the [Jodrell Bank glitch catalogue](http://www.jb.man.ac.uk/pulsar/glitches.html).
=> Added a function to parse the Jodrell Bank glitch catalogue

psrqpy/utils.py
Issue #36 -- read psrcat database file
=> Modified get_catalogue fn. to read db file

psrqpy/utils.py
=> Fix scaling in glitch table

psrqpy/__init__.py, psrqpy/search.py
=> Fix failure of Python 3 tests

psrqpy/search.py, psrqpy/utils.py
- minor fix to allow catalogue to accept a unicode hyphen in a number
- minor fix to make sure distance is not set from parallax if the
parallax is negative
- closes #56
=> Allow use to specify which pulsars to include on P-Pdot diagram

psrqpy/__init__.py, psrqpy/search.py, test/query_test.py
In astropy v4.0 there have been changes to the way that [masked columns](https://docs.astropy.org/en/stable/table/masking.html#table-masked-4-0) are assigned in tables. This PR attempts to fix these issues.
=> Fix astropy table issue

psrqpy/utils.py, test/query_test.py
This PR adds the ability to condition the query on the pulsar survey information.
- refs #68
=> Add survey and discovery to query

.github/workflows/pypi.yml, psrqpy/pulsar.py, psrqpy/search.py, psrqpy/utils.py, setup.py
=> Automate releases using github actions

psrqpy/config.py, psrqpy/search.py, psrqpy/utils.py, test/query_test.py
=> Adds derived GW parameters

docs/source/index.rst, psrqpy/config.py, psrqpy/utils.py, test/query_test.py
=> Add function to read MSP table

psrqpy/search.py, psrqpy/utils.py
=> Resolve "Switch numpy builtin types to Python types"

docs/source/index.rst, psrqpy/search.py, test/query_test.py
=> Resolve "Extend __getitem__"

psrqpy/utils.py
Allow *'s in the Period column of the globular cluster catalogue.
=> utils.py: allow asterisk in Period value

psrqpy/search.py, psrqpy/utils.py, setup.cfg
=> Resolve "Use appdirs package for setting the cache file location"

psrqpy/utils.py
This should solve my issue in #114. If this could be released as a new version ASAP, that would be super useful for my repository.
=> Added the ability to ask for specific version of the references

psrqpy/utils.py
=> Allow GC offset to have associated error

psrqpy/config.py
=> Update globular cluster table URL

psrqpy/utils.py
=> Ignore database lines that start with "WARNING"

README.md, docs/source/index.rst, psrqpy/config.py, psrqpy/search.py, psrqpy/utils.py
=> Update catalogue URL

psrqpy/search.py
This saves quite a few lines of code (and does not change behavior or compatibility as far as I know).
=> Use .setdefault for dicts in ppdot plotting code
